name: Run tests
on:
  push:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make install-requirements

      - name: Run tests
        run: make lint && make test
        env:
          MONGO_USER: ${{ vars.MONGO_USER }}
          MONGO_PASSWORD: ${{ vars.MONGO_PASSWORD }}
